-- Seed data for test and question tables
-- This file populates the database with sample psychological tests

-- Clear existing data (optional, uncomment if needed)
DELETE FROM "question";
DELETE FROM "test";

-- Test 1: GAD-7 (Anxiety)
INSERT INTO public.test (id, name, description, transcript, duration_mins, is_active, created_at, updated_at, position, category, questions_count)
VALUES ('19288da2-7ef9-44ad-9f1d-e4abd1b9a8b3', 'Шкала генерализованного тревожного расстройства (GAD-7)', 'Краткий опросник для оценки уровня тревожности за последние 2 недели', 'Оценка: 0-4 = минимальная, 5-9 = легкая, 10-14 = умеренная, 15-21 = тяжелая', '5', true, NOW(), NOW(), 0, 'EMOTIONS', 3);
INSERT INTO public.question (id, test_id, content, position) VALUES ('51240a24-f833-44be-87be-c331ffb1f8f1', '19288da2-7ef9-44ad-9f1d-e4abd1b9a8b3', '{"mod": "SCALE", "text": "Чувство нервозности, тревоги или напряжения", "type": "Choice", "options": [{"text": "Ни разу", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Несколько дней", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Более половины времени", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Почти каждый день", "type": "FullAnswer", "index": 3, "score": 3}]}', 0);
INSERT INTO public.question (id, test_id, content, position) VALUES ('14f95889-5d95-4eca-a33a-aa14f0460f39', '19288da2-7ef9-44ad-9f1d-e4abd1b9a8b3', '{"mod": "SCALE", "text": "Невозможность контролировать беспокойство", "type": "Choice", "options": [{"text": "Ни разу", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Несколько дней", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Более половины времени", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Почти каждый день", "type": "FullAnswer", "index": 3, "score": 3}]}', 1);
INSERT INTO public.question (id, test_id, content, position) VALUES ('2d9120ac-87dc-4d48-80f4-0a26e4a4e4ec', '19288da2-7ef9-44ad-9f1d-e4abd1b9a8b3', '{"mod": "SCALE", "text": "Чрезмерное беспокойство по разным поводам", "type": "Choice", "options": [{"text": "Ни разу", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Несколько дней", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Более половины времени", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Почти каждый день", "type": "FullAnswer", "index": 3, "score": 3}]}', 2);

-- Test 2: BDI (Depression)
INSERT INTO public.test (id, name, description, transcript, duration_mins, is_active, created_at, updated_at, position, category, questions_count)
VALUES ('a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d', 'Шкала депрессии Бека (BDI)', 'Опросник для определения уровня депрессии', 'Оценка: 0-9 = минимальная, 10-18 = легкая, 19-29 = умеренная, 30-63 = тяжелая', '10', true, NOW(), NOW(), 1, 'EMOTIONS', 5);
INSERT INTO public.question (id, test_id, content, position) VALUES ('f1a2b3c4-d5e6-4f7a-8b9c-0d1e2f3a4b5c', 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d', '{"mod": "SINGLE", "text": "Настроение", "type": "Choice", "options": [{"text": "Я не чувствую себя расстроенным", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Я расстроен", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Я все время расстроен", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Я настолько расстроен, что не могу это выдержать", "type": "FullAnswer", "index": 3, "score": 3}]}', 0);
INSERT INTO public.question (id, test_id, content, position) VALUES ('f2b3c4d5-e6f7-4a8b-9c0d-1e2f3a4b5c6d', 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d', '{"mod": "SINGLE", "text": "Пессимизм", "type": "Choice", "options": [{"text": "Я не тревожусь о своем будущем", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Я чувствую озадачен будущим", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Я чувствую, что ничего не ждет", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Мое будущее безнадежно", "type": "FullAnswer", "index": 3, "score": 3}]}', 1);
INSERT INTO public.question (id, test_id, content, position) VALUES ('f3c4d5e6-f7a8-4b9c-0d1e-2f3a4b5c6d7e', 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d', '{"mod": "SINGLE", "text": "Потеря интереса", "type": "Choice", "options": [{"text": "Я получаю удовольствие как раньше", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Я не получаю столько удовольствия", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Я больше не получаю удовольствия", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Я полностью не удовлетворен", "type": "FullAnswer", "index": 3, "score": 3}]}', 2);
INSERT INTO public.question (id, test_id, content, position) VALUES ('f4d5e6f7-a8b9-4c0d-1e2f-3a4b5c6d7e8f', 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d', '{"mod": "SINGLE", "text": "Усталость и утомляемость", "type": "Choice", "options": [{"text": "Я устаю не больше обычного", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Я устаю быстрее", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Я устаю почти от всего", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Я слишком устал, чтобы что-то делать", "type": "FullAnswer", "index": 3, "score": 3}]}', 3);
INSERT INTO public.question (id, test_id, content, position) VALUES ('f5e6f7a8-b9c0-4d1e-2f3a-4b5c6d7e8f9a', 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d', '{"mod": "SINGLE", "text": "Чувство неудачи", "type": "Choice", "options": [{"text": "Я не чувствую себя неудачником", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Я терпел больше неудач", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Я вижу в жизни много неудач", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Я полный неудачник", "type": "FullAnswer", "index": 3, "score": 3}]}', 4);

-- Test 3: PSS-10 (Stress)
INSERT INTO public.test (id, name, description, transcript, duration_mins, is_active, created_at, updated_at, position, category, questions_count)
VALUES ('b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', 'Шкала оценки стресса PSS-10', 'Опросник для определения уровня воспринимаемого стресса', 'Оценка: 0-13 = низкий, 14-26 = умеренный, 27-40 = высокий', '7', true, NOW(), NOW(), 2, 'EMOTIONS', 3);
INSERT INTO public.question (id, test_id, content, position) VALUES ('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d', 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', '{"mod": "SCALE", "text": "Как часто вы были расстроены из-за неожиданного?", "type": "Choice", "options": [{"text": "Никогда", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Почти никогда", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Иногда", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Довольно часто", "type": "FullAnswer", "index": 3, "score": 3}, {"text": "Очень часто", "type": "FullAnswer", "index": 4, "score": 4}]}', 0);
INSERT INTO public.question (id, test_id, content, position) VALUES ('b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e', 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', '{"mod": "SCALE", "text": "Как часто вы чувствовали неспособность контролировать важные вещи?", "type": "Choice", "options": [{"text": "Никогда", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Почти никогда", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Иногда", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Довольно часто", "type": "FullAnswer", "index": 3, "score": 3}, {"text": "Очень часто", "type": "FullAnswer", "index": 4, "score": 4}]}', 1);
INSERT INTO public.question (id, test_id, content, position) VALUES ('c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f', 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', '{"mod": "SCALE", "text": "Как часто вы чувствовали нервозность и стресс?", "type": "Choice", "options": [{"text": "Никогда", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Почти никогда", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "Иногда", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Довольно часто", "type": "FullAnswer", "index": 3, "score": 3}, {"text": "Очень часто", "type": "FullAnswer", "index": 4, "score": 4}]}', 2);

-- Test 4: Big Five (Personality)
INSERT INTO public.test (id, name, description, transcript, duration_mins, is_active, created_at, updated_at, position, category, questions_count)
VALUES ('c3d4e5f6-a7b8-5c9d-0e1f-2a3b4c5d6e7f', 'Тест Большой пятерки личностных черт', 'Оценка пяти основных измерений личности', 'Результаты по шкалам: экстраверсия, доброжелательность, добросовестность, нейротизм, открытость', '15', true, NOW(), NOW(), 3, 'PERSONALITY', 5);
INSERT INTO public.question (id, test_id, content, position) VALUES ('a1a2a3a4-a5a6-6b7b-1c2c-3d4d5e6e7f8f', 'c3d4e5f6-a7b8-5c9d-0e1f-2a3b4c5d6e7f', '{"mod": "SCALE", "text": "Я разговорчивый человек", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 0);
INSERT INTO public.question (id, test_id, content, position) VALUES ('b1b2b3b4-b5b6-7c8c-2d3d-4e5e6f7f8a9a', 'c3d4e5f6-a7b8-5c9d-0e1f-2a3b4c5d6e7f', '{"mod": "SCALE", "text": "Я склонен критиковать других", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 5}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 4}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 2}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 1}]}', 1);
INSERT INTO public.question (id, test_id, content, position) VALUES ('c1c2c3c4-c5c6-8d9d-3e4e-5f6f7a8a9b0b', 'c3d4e5f6-a7b8-5c9d-0e1f-2a3b4c5d6e7f', '{"mod": "SCALE", "text": "Я ответственный и организованный", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 2);
INSERT INTO public.question (id, test_id, content, position) VALUES ('d1d2d3d4-d5d6-9e0e-4f5f-6a7a8b9b0c1c', 'c3d4e5f6-a7b8-5c9d-0e1f-2a3b4c5d6e7f', '{"mod": "SCALE", "text": "Я легко расстраиваюсь", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 5}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 4}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 2}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 1}]}', 3);
INSERT INTO public.question (id, test_id, content, position) VALUES ('e1e2e3e4-e5e6-0f1f-5a6a-7b8b9c0c1d2d', 'c3d4e5f6-a7b8-5c9d-0e1f-2a3b4c5d6e7f', '{"mod": "SCALE", "text": "Я открыт новым идеям и опыту", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 4);

-- Test 5: EQ (Emotional Intelligence)
INSERT INTO public.test (id, name, description, transcript, duration_mins, is_active, created_at, updated_at, position, category, questions_count)
VALUES ('d4e5f6a7-a8b9-6c0d-1e2f-3a4b5c6d7e8f', 'Тест эмоционального интеллекта', 'Оценка способности распознавать и управлять эмоциями', 'Высокий EQ (80-100), средний (60-79), низкий (ниже 60)', '10', true, NOW(), NOW(), 4, 'DEVELOPMENT', 4);
INSERT INTO public.question (id, test_id, content, position) VALUES ('f1f2f3f4-f5f6-1a2a-6b7b-8c9c0d1d2e3e', 'd4e5f6a7-a8b9-6c0d-1e2f-3a4b5c6d7e8f', '{"mod": "SCALE", "text": "Я понимаю свои эмоции", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 0);
INSERT INTO public.question (id, test_id, content, position) VALUES ('a1a2a3a5-a6a7-2b3b-7c8c-9d0d1e2e3f4f', 'd4e5f6a7-a8b9-6c0d-1e2f-3a4b5c6d7e8f', '{"mod": "SCALE", "text": "Я могу управлять своими эмоциями", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 1);
INSERT INTO public.question (id, test_id, content, position) VALUES ('b1b2b3b5-b6b7-3c4c-8d9d-0e1e2f3f4a5a', 'd4e5f6a7-a8b9-6c0d-1e2f-3a4b5c6d7e8f', '{"mod": "SCALE", "text": "Я чувствую эмоции других людей", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 2);
INSERT INTO public.question (id, test_id, content, position) VALUES ('c1c2c3c5-c6c7-4d5d-9e0e-1f2f3a4a5b6b', 'd4e5f6a7-a8b9-6c0d-1e2f-3a4b5c6d7e8f', '{"mod": "SCALE", "text": "Я мотивирован достигать свои цели", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 3);

-- Test 6: Self-Esteem (Development)
INSERT INTO public.test (id, name, description, transcript, duration_mins, is_active, created_at, updated_at, position, category, questions_count)
VALUES ('e5f6a7b8-b9c0-7d1e-2f3a-4b5c6d7e8f9a', 'Тест самооценки Розенберга', 'Оценка уровня самооценки и уверенности в себе', 'Высокая самооценка (30-40), средняя (16-29), низкая (ниже 15)', '5', true, NOW(), NOW(), 5, 'DEVELOPMENT', 3);
INSERT INTO public.question (id, test_id, content, position) VALUES ('d1d2d3d5-d6d7-5e6e-0f1f-2a3a4b5b6c7c', 'e5f6a7b8-b9c0-7d1e-2f3a-4b5c6d7e8f9a', '{"mod": "SCALE", "text": "Я чувствую, что я человек достоинства", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Согласен", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 3, "score": 4}]}', 0);
INSERT INTO public.question (id, test_id, content, position) VALUES ('e1e2e3e5-e6e7-6f7f-1a2a-3b4b5c6c7d8d', 'e5f6a7b8-b9c0-7d1e-2f3a-4b5c6d7e8f9a', '{"mod": "SCALE", "text": "Я доволен собой в целом", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Согласен", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 3, "score": 4}]}', 1);
INSERT INTO public.question (id, test_id, content, position) VALUES ('f1f2f3f5-f6f7-7a8a-2b3b-4c5c6d7d8e9e', 'e5f6a7b8-b9c0-7d1e-2f3a-4b5c6d7e8f9a', '{"mod": "SCALE", "text": "Я считаю, что я неудачник", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 4}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 3}, {"text": "Согласен", "type": "FullAnswer", "index": 2, "score": 2}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 3, "score": 1}]}', 2);

-- Test 7: Career Interests (Career)
INSERT INTO public.test (id, name, description, transcript, duration_mins, is_active, created_at, updated_at, position, category, questions_count)
VALUES ('f6a7b8c9-c0d1-8e2f-3a4b-5c6d7e8f9a0b', 'Опросник карьерных интересов', 'Определение профессиональных склонностей и интересов', 'Результаты показывают соответствие профилю профессий', '12', true, NOW(), NOW(), 6, 'CAREER', 4);
INSERT INTO public.question (id, test_id, content, position) VALUES ('a1a2a3a6-a7a8-8b9b-3c4c-5d6d7e8e9f0f', 'f6a7b8c9-c0d1-8e2f-3a4b-5c6d7e8f9a0b', '{"mod": "SCALE", "text": "Мне нравится работать с людьми", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 0);
INSERT INTO public.question (id, test_id, content, position) VALUES ('b1b2b3b6-b7b8-9c0c-4d5d-6e7e8f9f0a1a', 'f6a7b8c9-c0d1-8e2f-3a4b-5c6d7e8f9a0b', '{"mod": "SCALE", "text": "Я люблю аналитическую работу", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 1);
INSERT INTO public.question (id, test_id, content, position) VALUES ('c1c2c3c6-c7c8-0d1d-5e6e-7f8f9a0a1b2b', 'f6a7b8c9-c0d1-8e2f-3a4b-5c6d7e8f9a0b', '{"mod": "SCALE", "text": "Я хочу иметь высокий доход", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 2);
INSERT INTO public.question (id, test_id, content, position) VALUES ('d1d2d3d6-d7d8-1e2e-6f7f-8a9a0b1b2c3c', 'f6a7b8c9-c0d1-8e2f-3a4b-5c6d7e8f9a0b', '{"mod": "SCALE", "text": "Я готов работать в команде", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 3);

-- Test 8: Communication Skills (Relationships)
INSERT INTO public.test (id, name, description, transcript, duration_mins, is_active, created_at, updated_at, position, category, questions_count)
VALUES ('a7b8c9d0-d1e2-9f3a-4b5c-6d7e8f9a0b1c', 'Тест навыков коммуникации', 'Оценка эффективности коммуникативных навыков', 'Результаты показывают уровень развития коммуникативных умений', '8', true, NOW(), NOW(), 7, 'RELATIONSHIPS', 3);
INSERT INTO public.question (id, test_id, content, position) VALUES ('e1e2e3e6-e7e8-2f3f-7a8a-9b0b1c2c3d4d', 'a7b8c9d0-d1e2-9f3a-4b5c-6d7e8f9a0b1c', '{"mod": "SCALE", "text": "Я хорошо слушаю других", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 0);
INSERT INTO public.question (id, test_id, content, position) VALUES ('f1f2f3f6-f7f8-3a4a-8b9b-0c1c2d3d4e5e', 'a7b8c9d0-d1e2-9f3a-4b5c-6d7e8f9a0b1c', '{"mod": "SCALE", "text": "Я четко выражаю свои мысли", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 1);
INSERT INTO public.question (id, test_id, content, position) VALUES ('a1a2a3a7-a8a9-4b5b-9c0c-1d2d3e4e5f6f', 'a7b8c9d0-d1e2-9f3a-4b5c-6d7e8f9a0b1c', '{"mod": "SCALE", "text": "Я могу разрешать конфликты", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 2);

-- Test 9: Motivation (Development)
INSERT INTO public.test (id, name, description, transcript, duration_mins, is_active, created_at, updated_at, position, category, questions_count)
VALUES ('b8c9d0e1-e2f3-0a4b-5c6d-7e8f9a0b1c2d', 'Опросник личной мотивации', 'Определение уровня мотивации к деятельности', 'Результаты показывают внутреннюю и внешнюю мотивацию', '10', true, NOW(), NOW(), 8, 'DEVELOPMENT', 4);
INSERT INTO public.question (id, test_id, content, position) VALUES ('b1b2b3b7-b8b9-5c6c-0d1d-2e3e4f5f6a7a', 'b8c9d0e1-e2f3-0a4b-5c6d-7e8f9a0b1c2d', '{"mod": "SCALE", "text": "Я стремлюсь достичь своих целей", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 0);
INSERT INTO public.question (id, test_id, content, position) VALUES ('c1c2c3c7-c8c9-6d7d-1e2e-3f4f5a6a7b8b', 'b8c9d0e1-e2f3-0a4b-5c6d-7e8f9a0b1c2d', '{"mod": "SCALE", "text": "Я получаю удовольствие от сложных задач", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 1);
INSERT INTO public.question (id, test_id, content, position) VALUES ('d1d2d3d7-d8d9-7e8e-2f3f-4a5a6b7b8c9c', 'b8c9d0e1-e2f3-0a4b-5c6d-7e8f9a0b1c2d', '{"mod": "SCALE", "text": "Я постоянно развиваюсь и обучаюсь", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 2);
INSERT INTO public.question (id, test_id, content, position) VALUES ('e1e2e3e7-e8e9-8f0f-3a4a-5b6b7c8c9d0d', 'b8c9d0e1-e2f3-0a4b-5c6d-7e8f9a0b1c2d', '{"mod": "SCALE", "text": "Я настойчив перед лицом трудностей", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 3);

-- Test 10: Cognitive Abilities (Intellect)
INSERT INTO public.test (id, name, description, transcript, duration_mins, is_active, created_at, updated_at, position, category, questions_count)
VALUES ('c9d0e1f2-f3a4-1b5c-6d7e-8f9a0b1c2d3e', 'Тест когнитивных способностей', 'Оценка логического мышления и решения проблем', 'Результаты показывают уровень развития интеллекта', '15', true, NOW(), NOW(), 9, 'INTELLECT', 4);
INSERT INTO public.question (id, test_id, content, position) VALUES ('f1f2f3f7-f8f9-0a1a-4b5b-6c7c8d9d0e1e', 'c9d0e1f2-f3a4-1b5c-6d7e-8f9a0b1c2d3e', '{"mod": "SINGLE", "text": "Какой следующий в последовательности?", "type": "Choice", "options": [{"text": "А", "type": "FullAnswer", "index": 0, "score": 0}, {"text": "Б", "type": "FullAnswer", "index": 1, "score": 1}, {"text": "В", "type": "FullAnswer", "index": 2, "score": 1}, {"text": "Г", "type": "FullAnswer", "index": 3, "score": 1}]}', 0);
INSERT INTO public.question (id, test_id, content, position) VALUES ('a1a2a3a8-a9a0-1b2b-5c6c-7d8d9e0e1f2f', 'c9d0e1f2-f3a4-1b5c-6d7e-8f9a0b1c2d3e', '{"mod": "SINGLE", "text": "Может ли вода быть твердой?", "type": "Choice", "options": [{"text": "Да", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Нет", "type": "FullAnswer", "index": 1, "score": 0}, {"text": "Иногда", "type": "FullAnswer", "index": 2, "score": 0}, {"text": "Не знаю", "type": "FullAnswer", "index": 3, "score": 0}]}', 1);
INSERT INTO public.question (id, test_id, content, position) VALUES ('b1b2b3b8-b9b0-2c3c-6d7d-8e9e0f1f2a3a', 'c9d0e1f2-f3a4-1b5c-6d7e-8f9a0b1c2d3e', '{"mod": "SCALE", "text": "Я хорошо справляюсь с логическими задачами", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 2);
INSERT INTO public.question (id, test_id, content, position) VALUES ('c1c2c3c8-c9c0-3d4d-7e8e-9f0f1a2a3b4b', 'c9d0e1f2-f3a4-1b5c-6d7e-8f9a0b1c2d3e', '{"mod": "SCALE", "text": "Я быстро понимаю новую информацию", "type": "Choice", "options": [{"text": "Совершенно не согласен", "type": "FullAnswer", "index": 0, "score": 1}, {"text": "Скорее не согласен", "type": "FullAnswer", "index": 1, "score": 2}, {"text": "Нейтрален", "type": "FullAnswer", "index": 2, "score": 3}, {"text": "Скорее согласен", "type": "FullAnswer", "index": 3, "score": 4}, {"text": "Полностью согласен", "type": "FullAnswer", "index": 4, "score": 5}]}', 3);
